### ISSUE TITLE
Images are not loaded in new version

### ISSUE THREAD

**Issue by OMID-F** [VasylTech/advanced-access-manager#1]
Hi,
i use this plugin without issue. today i do update to latest version from WP ...
but now images are not loaded !  unless disable the plugin.

web server error:
[fcgid:warn] mod_fcgid: stderr: PHP Warning:  file_get_contents(/xxxx/2015/06/yyyyyy.jpg): failed to open stream: No such file or directory in /plugins/advanced-access-manager/extension/AAM_Media_Manager/extension.php on line 276

**Comment by VasylTech** [comment]
Hi there,

In order to have media files protected physically, AAM Media Manager overwrites the direct URL to media file and routes it through the PHP script that authenticate a request.

Please verify that the file that is mentioned in your warning actually physically exists and is readable.

Regards,
Vasyl

**Comment by OMID-F** [comment]
yes files are physically exists. when i disable the plugin all fine.

1 other thing, i do change WP uploads folder path form config.php file, this can be problem?
<php>define( 'UPLOADS', ''.'newpath/uploads' );</php>

**Comment by OMID-F** [comment]
update to latest versions:
no issue on (Wordpress 4.3.1) and (Advanced Access Manager 2.9.2)
